version: "3.9"
services:
    postgres:
        container_name: forum_postgres_container_20672
        image: postgres:15
        working_dir: /app
        restart: always
        ports:
            - "20672:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - "postgres_forum_20672:/var/lib/postgresql"

volumes:
    postgres_forum_20672:
